server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
cors:
  allowed-origins:
    - http://localhost:5173
    - capacitor://localhost
    - http://localhost
jwt:
  secret: ${JWT_SECRET}
firebase:
  config-json: ${FIREBASE_CONFIG_JSON:}