server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myapp}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop
cors:
  allowed-origins:
    - http://localhost:5173
    - capacitor://localhost
    - http://localhost
jwt:
  secret: ${JWT_SECRET}
firebase:
  config-json: ${FIREBASE_CONFIG_JSON:}