server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
jwt:
  secret: ${JWT_SECRET}
firebase:
  config-path: ${FIREBASE_CONFIG_PATH:}