spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
cors:
  allowed-origins:
    - http://localhost:5173
    - capacitor://localhost
    - http://localhost
jwt:
  secret: ${JWT_SECRET}